# General plugin configuration
# prefix: "[MuMc]"

# Configuration version
# config-version: 1

# Plugin language [en, es, other]
language: "en"

spawn:
  enabled: false
  # Name of the world where mobs will spawn
  world: "world"
  # Time interval for mob spawning (1d = 1440 minutes)
  interval: 1440
  # Mob spawning radius
  radius: 10
  # Mob spawn chance
  chance: 100
  # Reference position for mob spawning
  location:
    # X
    x: -80
    # Y
    y: 83
    # Z
    z: 277
  # Percentage of King spawns
  king_percentage: 30
  # Percentage of Emperor spawns
  # emperor_percentage = (100%) - (king_percentage)